build_from:
  aarch64: "ghcr.io/sudoxnym/ankermake-m5-protocol:exiles"
  amd64: "ghcr.io/sudoxnym/ankermake-m5-protocol:exiles"
  armv7: "ghcr.io/sudoxnym/ankermake-m5-protocol:exiles"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ankerctl"
  org.opencontainers.image.description: "An add-on to control Anker devices via Home Assistant"
  org.opencontainers.image.source: "https://github.com/sudoxnym/exiles-ankerctl-hassio-addons"
  org.opencontainers.image.licenses: "GPLv3"
